"""ASL-backed functional model for PTO instruction validation."""

from .backend import (
    AslBackend,
    BackendAvailability,
    BackendResult,
    DifferentialBackend,
    FunctionalBackend,
    NativeBackend,
)
from .cases import CaseRegistry, ModelCase
from .runner import BatchReport, run_cases
from .session import (
    AslSession,
    EmbeddedAslSession,
    ProcessAslSession,
    SessionClosedError,
    SessionError,
    SessionSnapshot,
    SessionStepResult,
)
from .state import (
    ArchitectureState,
    BlockState,
    ExecutionResult,
    FaultState,
    MemoryEffect,
    MemoryRegion,
    MemoryState,
    ScalarState,
    SharedState,
    SharedTile,
    StateEnvelope,
    TileDescriptor,
    TileState,
    TileValue,
    canonical_hash,
    canonical_json,
    state_diff,
)
from .paths import cache_root, repository_root, resolve_pto_spec
from .runtime import (
    CallbackSemanticBackend,
    ElfLoadRequest,
    GuestMemory,
    GuestRegion,
    HostMemoryBridge,
    HostAdapter,
    InstructionRequest,
    InstructionTransaction,
    MemoryAccessError,
    MemorySnapshot,
    MemoryTransaction,
    MemoryWorker,
    MockHostAdapter,
    ProgramImage,
    ProgramSegment,
    RuntimeAdapter,
    RuntimeClosedError,
    RuntimeErrorBase,
    RuntimeSnapshot,
    SemanticBackend,
    StackImage,
    TransactionError,
    AslMultiPeElfRunner,
    AslModelProfile,
    AslWorkerExecutor,
    CallbackFinisher,
    ControlFlowPolicy,
    ExecutionFinisher,
    FinisherPolicy,
    InstructionExecution,
    InstructionExecutor,
    MultiPeRunResult,
    MultiPeStep,
    PeContext,
    SequentialControlFlow,
    UnsupportedPeStateScope,
)

__all__ = [
    "AslBackend",
    "BackendAvailability",
    "BackendResult",
    "CaseRegistry",
    "DifferentialBackend",
    "FunctionalBackend",
    "ModelCase",
    "BatchReport",
    "run_cases",
    "NativeBackend",
    "AslSession",
    "EmbeddedAslSession",
    "ProcessAslSession",
    "SessionClosedError",
    "SessionError",
    "SessionSnapshot",
    "SessionStepResult",
    "ArchitectureState",
    "BlockState",
    "ExecutionResult",
    "FaultState",
    "MemoryEffect",
    "MemoryRegion",
    "MemoryState",
    "ScalarState",
    "SharedState",
    "SharedTile",
    "StateEnvelope",
    "TileDescriptor",
    "TileState",
    "TileValue",
    "canonical_hash",
    "canonical_json",
    "state_diff",
    "CallbackSemanticBackend", "ElfLoadRequest", "GuestMemory", "GuestRegion",
    "HostAdapter", "InstructionRequest", "InstructionTransaction",
    "HostMemoryBridge", "MemoryWorker", "StackImage",
    "MemoryAccessError", "MemorySnapshot", "MemoryTransaction", "MockHostAdapter",
    "ProgramImage", "ProgramSegment", "RuntimeAdapter", "RuntimeClosedError",
    "RuntimeErrorBase", "RuntimeSnapshot", "SemanticBackend", "TransactionError",
    "AslMultiPeElfRunner", "AslWorkerExecutor", "CallbackFinisher",
    "AslModelProfile",
    "ControlFlowPolicy", "ExecutionFinisher", "FinisherPolicy",
    "InstructionExecution", "InstructionExecutor", "MultiPeRunResult",
    "MultiPeStep", "PeContext", "SequentialControlFlow", "UnsupportedPeStateScope",
    "cache_root", "repository_root", "resolve_pto_spec",
]
